import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { supportedApps } from "../../constants/supportedApps";
const initialState = {
  app: {},
  tag: "latest",
  source: "./",
  destination: "./",
  directory: "/usr/app",
  port: "3000",
  output: "main",
  env: {},
  command: "",
  isLoading: false,
};

export const appSlice = createSlice({
  name: "app",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Use the PayloadAction type to declare the contents of `action.payload`
    loadApp: (state, action: PayloadAction<string>) => {
      state.app = (supportedApps as any)[action.payload];
      console.log(state.app);
    },
    setVar: (state, action: PayloadAction<{ type: string; val: string }>) => {
      (state as any)[action.payload.type] = action.payload.val;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  //   extraReducers: (builder) => {
  //     builder
  //       .addCase(incrementAsync.pending, (state) => {
  //         state.status = "loading";
  //       })
  //       .addCase(incrementAsync.fulfilled, (state, action) => {
  //         state.status = "idle";
  //         state.value += action.payload;
  //       })
  //       .addCase(incrementAsync.rejected, (state) => {
  //         state.status = "failed";
  //       });
  //   },
});

export const { loadApp, setVar } = appSlice.actions;
export const selectAppSlice = (state: any) => state.app;
export default appSlice.reducer;
// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// i
